workflows:
  ios-workflow:
    name: Jibli Stats iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_auth # تأكد أن هذا هو اسم المجموعة التي أضفت فيها المتغيرات في الموقع
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Set up code signing
        script: |
          keychain initialize
          # جلب ملفات التوقيع باستخدام المتغيرات
          app-store-connect fetch-signing-files "com.jibli_stats" --publish-type app-store --create
          export_signing_files
      - name: Build iOS IPA
        script: |
          flutter build ios --release --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: manual # عدنا لـ manual ولكن سنحذف الحقول التي تسبب الخطأ
      email:
        recipients:
          - djilanibenhacine5@gmail.com